# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        public: false       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    GollumSF\RestDocBundle\Controller\:
        autowire: true
        public: false
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    GollumSF\RestDocBundle\TypeDiscover\TypeDiscoverInterface:
        class: GollumSF\RestDocBundle\TypeDiscover\TypeDiscover

    GollumSF\RestDocBundle\TypeDiscover\Handler\AnnotationHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\TypeDiscover\TypeDiscoverInterface::HANDLER_TAG', priority: 10 }

    GollumSF\RestDocBundle\TypeDiscover\Handler\DoctrineHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\TypeDiscover\TypeDiscoverInterface::HANDLER_TAG', priority: 20 }

    GollumSF\RestDocBundle\TypeDiscover\Handler\PropertyInfosHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\TypeDiscover\TypeDiscoverInterface::HANDLER_TAG', priority: 30 }
    
    GollumSF\RestDocBundle\Reflection\ControllerActionExtractorInterface:
        class: GollumSF\RestDocBundle\Reflection\ControllerActionExtractor

    GollumSF\RestDocBundle\Generator\OpenApiGeneratorInterface:
        class: GollumSF\RestDocBundle\Generator\OpenApiGenerator

    GollumSF\RestDocBundle\Generator\Parameters\ParametersGeneratorInterface:
        class: GollumSF\RestDocBundle\Generator\Parameters\ParametersGenerator

    GollumSF\RestDocBundle\Generator\Parameters\Handler\UrlHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\Parameters\ParametersGeneratorInterface::HANDLER_TAG', priority: 10 }

    GollumSF\RestDocBundle\Generator\Parameters\Handler\CollectionHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\Parameters\ParametersGeneratorInterface::HANDLER_TAG', priority: 20 }

    GollumSF\RestDocBundle\Generator\Parameters\Handler\RequestPropertiesHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\Parameters\ParametersGeneratorInterface::HANDLER_TAG', priority: 30 }

    GollumSF\RestDocBundle\Generator\ResponseProperties\ResponsePropertiesGeneratorInterface:
        class: GollumSF\RestDocBundle\Generator\ResponseProperties\ResponsePropertiesGenerator

    GollumSF\RestDocBundle\Generator\ResponseProperties\Handler\GroupHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\ResponseProperties\ResponsePropertiesGeneratorInterface::HANDLER_TAG', priority: 10 }

    GollumSF\RestDocBundle\Generator\ResponseProperties\Handler\ResponsePropertiesHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\ResponseProperties\ResponsePropertiesGeneratorInterface::HANDLER_TAG', priority: 20 }

    GollumSF\RestDocBundle\Generator\ResponseProperties\Handler\CollectionHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\ResponseProperties\ResponsePropertiesGeneratorInterface::HANDLER_TAG', priority: 255 }

    GollumSF\RestDocBundle\Generator\RequestBody\RequestBodyGeneratorInterface:
        class: GollumSF\RestDocBundle\Generator\RequestBody\RequestBodyGenerator

    GollumSF\RestDocBundle\Generator\RequestBody\Handler\GroupHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\RequestBody\RequestBodyGeneratorInterface::HANDLER_TAG', priority: 10 }

    GollumSF\RestDocBundle\Generator\RequestBody\Handler\RequestBodyPropertiesHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\RequestBody\RequestBodyGeneratorInterface::HANDLER_TAG', priority: 20 }

    GollumSF\RestDocBundle\Builder\MetadataBuilder\MetadataBuilderInterface:
        class: GollumSF\RestDocBundle\Builder\MetadataBuilder\MetadataBuilder

    GollumSF\RestDocBundle\Builder\MetadataBuilder\Handler\AnnotationHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Builder\MetadataBuilder\MetadataBuilderInterface::HANDLER_TAG' }

    GollumSF\RestDocBundle\Builder\ModelBuilder\ModelBuilderInterface:
        class: GollumSF\RestDocBundle\Builder\ModelBuilder\ModelBuilder

    GollumSF\RestDocBundle\Builder\ModelBuilder\Decorator\PropertyDecorator:
        arguments:
            $nameConverter: '@serializer.name_converter.metadata_aware'
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Builder\ModelBuilder\ModelBuilderInterface::DECORATOR_TAG' }
        
    GollumSF\RestDocBundle\Builder\TagBuilder\TagBuilderInterface:
        class: GollumSF\RestDocBundle\Builder\TagBuilder\TagBuilder
        
    GollumSF\RestDocBundle\Builder\TagBuilder\Decorator\AnnotationDecorator:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Builder\TagBuilder\TagBuilderInterface::DECORATOR_TAG' }