# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        public: false       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    GollumSF\RestDocBundle\Controller\:
        autowire: true
        public: false
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    GollumSF\RestDocBundle\TypeDiscover\TypeDiscoverInterface:
        class: GollumSF\RestDocBundle\TypeDiscover\TypeDiscover

    GollumSF\RestDocBundle\TypeDiscover\Handler\AnnotationHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\TypeDiscover\TypeDiscoverInterface::HANDLER_TAG', priority: 10 }

    GollumSF\RestDocBundle\TypeDiscover\Handler\DoctrineHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\TypeDiscover\TypeDiscoverInterface::HANDLER_TAG', priority: 20 }

    GollumSF\RestDocBundle\Reflection\ControllerActionExtractorInterface:
        class: GollumSF\RestDocBundle\Reflection\ControllerActionExtractor

    GollumSF\RestDocBundle\Generator\OpenApiGeneratorInterface:
        class: GollumSF\RestDocBundle\Generator\OpenApiGenerator

    GollumSF\RestDocBundle\Generator\MetadataBuilder\MetadataBuilderInterface:
        class: GollumSF\RestDocBundle\Generator\MetadataBuilder\MetadataBuilder

    GollumSF\RestDocBundle\Generator\MetadataBuilder\Handler\AnnotationHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\MetadataBuilder\MetadataBuilderInterface::HANDLER_TAG' }

    GollumSF\RestDocBundle\Generator\ModelBuilder\ModelBuilderInterface:
        class: GollumSF\RestDocBundle\Generator\ModelBuilder\ModelBuilder

    GollumSF\RestDocBundle\Generator\ModelBuilder\Decorator\PropertyDecorator:
        arguments:
            $nameConverter: '@serializer.name_converter.metadata_aware'
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\ModelBuilder\ModelBuilderInterface::DECORATOR_TAG' }
        
    GollumSF\RestDocBundle\Generator\TagBuilder\TagBuilderInterface:
        class: GollumSF\RestDocBundle\Generator\TagBuilder\TagBuilder
        
    GollumSF\RestDocBundle\Generator\TagBuilder\Decorator\AnnotationDecorator:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Generator\TagBuilder\TagBuilderInterface::DECORATOR_TAG' }