# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        public: false       # Allows optimizing the container by removing unused services; this also means
        # fetching services directly from the container via $container->get() won't work.
        # The best practice is to be explicit about your dependencies anyway.

    GollumSF\RestDocBundle\Controller\:
        autowire: true
        public: false
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    GollumSF\RestDocBundle\Generator\OpenApiGeneratorInterface:
        class: GollumSF\RestDocBundle\Generator\OpenApiGenerator
        arguments:
            $nameConverter: '@serializer.name_converter.metadata_aware'

    GollumSF\RestDocBundle\Reflection\ControllerActionExtractorInterface:
        class: GollumSF\RestDocBundle\Reflection\ControllerActionExtractor

    GollumSF\RestDocBundle\Metadata\MetadataFactoryInterface:
        class: GollumSF\RestDocBundle\Metadata\MetadataFactory

    GollumSF\RestDocBundle\Metadata\Handler\AnnotationHandler:
        tags:
            - { name: !php/const 'GollumSF\RestDocBundle\Metadata\MetadataFactoryInterface::HANDLER_TAG' }